---
resource_types:
- name: s3-iam
  type: docker-image
  source:
    repository: governmentpaas/s3-resource
    tag: 594eaa9f4d93b2ed32a7e5e1cdea5b380e2f6682

- name: semver-iam
  type: docker-image
  source:
    repository: governmentpaas/semver-resource
    tag: ecbdd201e122b44de99a40ac9f24407c1a43b9a2

resources:
  - name: paas-cf
    type: git
    source:
      uri: https://github.com/alphagov/paas-cf.git
      branch: master
      tag_filter: ((paas_cf_tag_filter))
      commit_verification_key_ids: ((gpg_ids))

  - name: cf-secrets
    type: s3-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      versioned_file: cf-secrets.yml

  - name: cf-manifest
    type: s3-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      versioned_file: cf-manifest.yml

  - name: delete-timer
    type: time
    source:
      start: 20:00 -0000
      stop: 6:00 -0000
      interval: 2h

  - name: bosh-secrets
    type: s3-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      versioned_file: bosh-secrets.yml

  - name: bosh-CA
    type: s3-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      versioned_file: bosh-CA.tar.gz

  - name: deployed-healthcheck
    type: s3-iam
    source:
      bucket: ((state_bucket))
      region_name: ((aws_region))
      versioned_file: healthcheck-deployed

  - name: datadog-tfstate
    type: s3-iam
    source:
      bucket: ((state_bucket))
      versioned_file: datadog.tfstate
      region_name: eu-west-1

jobs:
  - name: delete
    serial: true
    plan:
      - get: delete-timer
        trigger: true
      - get: bosh-secrets
      - get: paas-cf
      - get: cf-secrets
      - get: cf-manifest
      - get: bosh-CA
      - get: datadog-tfstate

      - task: get-cf-cli-config
        file: paas-cf/concourse/tasks/get-cf-cli-config.yml

      - task: remove-healthcheck-db
        file: paas-cf/concourse/tasks/remove-healthcheck-db.yml

      - task: datadog-TF-destroy
        file: paas-cf/concourse/tasks/terraform_destroy_datadog.yml
        params:
          TF_VAR_datadog_api_key: ((datadog_api_key))
          TF_VAR_datadog_app_key: ((datadog_app_key))
          TF_VAR_env: ((deploy_env))
          TF_VAR_aws_account: ((aws_account))
          ENABLE_DATADOG: ((enable_datadog))
        ensure:
          put: datadog-tfstate
          params:
            file: updated-datadog-tfstate/datadog.tfstate

      - task: await-turn
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/bosh-cli
              tag: 465642da06051a55630d39c899697b678f66a7f7
          inputs:
            - name: paas-cf
          params:
            DEPLOY_ENV: ((deploy_env))
          run:
            path: ./paas-cf/concourse/scripts/sleep_for_deploy_env.sh

      - task: delete-deployment
        config:
          platform: linux
          inputs:
            - name: delete-timer
            - name: bosh-secrets
            - name: paas-cf
          outputs:
            - name: deployed-healthcheck
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/bosh-cli
              tag: 465642da06051a55630d39c899697b678f66a7f7
          run:
            path: sh
            args:
              - -e
              - -c
              - |
                ./paas-cf/concourse/scripts/bosh_login.sh "((bosh_fqdn))" bosh-secrets/bosh-secrets.yml
                bosh -n delete deployment "((deploy_env))" --force

                echo "no" > deployed-healthcheck/healthcheck-deployed
        on_success:
          put: deployed-healthcheck
          params:
            file: deployed-healthcheck/healthcheck-deployed

      - task: shutdown-rds-instances
        config:
          platform: linux
          inputs:
            - name: paas-cf
          params:
            AWS_DEFAULT_REGION: ((aws_region))
            DEPLOY_ENV: ((deploy_env))
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/awscli
              tag: 1ab7d6cdac70f2c32563ea173da0cd7791309be5
          run:
            path: ./paas-cf/concourse/scripts/rds_instances.sh
            args:
              - stop
